import Head from 'next/head'
import { GetStaticProps } from 'next'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Product } from '@/components/product/types'
import api from './api/api'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })


interface Props{
  products: Product[]
}

function parseCurrency(value: number):string {
  return value.toLocaleString('es-EC',{
    style: "currency",
    currency: "USD"
  })
}

const IndexRoute: React.FC<Props>=({products})=>{

  const [cart, setCart]=React.useState<Product[]>([])
  const text=React.useMemo(()=>{
    return cart
    .reduce((message, product)=>message.concat(`* ${product.title}- ${parseCurrency(product.price)}\n`), "")
    .concat(`\nTotal: ${parseCurrency(cart.reduce((total, product)=>total + product.price, 0))}`)
  }, [cart])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <header className={styles.header}>
        <nav className={styles.nav}>
          <ul className={styles.menu}>
            <li>Home</li>
            <li>About</li>
            <li>Catalogo</li>
          </ul>
        </nav> 
      </header>
        <section className={styles.grid_products}>{products.map((product)=>(
          <article key={product.id} className={styles.product}>
            <h1>{product.title}</h1>
            <strong>{parseCurrency(product.price)}</strong>
            <p>{product.description}</p>
            <button onClick={()=>setCart((cart)=>cart.concat(product))}>
              Agregar
            </button>
          </article>
        ))}</section>
        {
          Boolean(cart.length) && (
          <a target={"_blank"} href={`https://wa.me/593995700017?text=${encodeURIComponent(text)}`}>Completar la compra</a>
          )
        }

      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps =async () => {
  const products= await api.list()
  return {
    props: {
      products
    },
    revalidate: 10
  }
}

export default IndexRoute